In [1]:
import numpy as np

In [3]:
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

## np.zeros()

In [9]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## np,.ones()

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np. ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## np.empty()

In [18]:
np.empty(5)

array([2.12199579e-314, 0.00000000e+000, 4.03157567e-321, 1.00582601e-311,
       0.00000000e+000])

## np.arange()

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

## np.rand()

In [19]:
np.random.rand(3, 5)

array([[0.31688106, 0.31437004, 0.82329029, 0.51119758, 0.77946524],
       [0.35419719, 0.9621867 , 0.25005526, 0.67542995, 0.48536733],
       [0.90083934, 0.29048089, 0.00313882, 0.03128248, 0.81319332]])

In [22]:
np.random.rand(4, 5)

array([[0.64881   , 0.93917211, 0.26924735, 0.52690163, 0.05883182],
       [0.25871691, 0.05681753, 0.70682186, 0.7188263 , 0.22493787],
       [0.43756021, 0.53975493, 0.23107776, 0.21943314, 0.893532  ],
       [0.55306724, 0.46571659, 0.82906447, 0.40002392, 0.75307779]])

In [24]:
ary = np.random.rand(5)
print(ary)
print(np.all(ary >= 0.3))
print(np.any(ary >= 0.7))

[0.25219109 0.37795168 0.95934858 0.69068283 0.48558042]
False
True


In [26]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
arr2 = np.arange(100)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
arr2.reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
arr2.reshape(5, 20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [32]:
arr2 = np.arange(16)
arr2.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## shape(), dtype(), astype()

In [34]:
arr = np.arange(10)

In [35]:
arr.shape

(10,)

In [36]:
arr.dtype

dtype('int32')

In [39]:
arr.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
arr.dtype

dtype('int32')

In [43]:
x = np.array([2, 3, 5, 7, 9])
print(x.mean())

5.2


In [44]:
print(x.shape)

(5,)


In [45]:
x = np.array([1, 3, 5, 7, 9, 11]).reshape(3, 2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [46]:
x = np.array([[1, 3, 5], [2, 4, 6]])
print(x)

[[1 3 5]
 [2 4 6]]


In [47]:
print(x[1])

[2 4 6]


In [48]:
y = np.ones([3, 4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [50]:
print(x[1].mean())
print(x.mean())
print(x.shape)

4.0
3.5
(2, 3)


In [51]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
# 기본 인덱스
arr[5]

5

In [53]:
# 마이너스 인덱스
arr[-1]

15

In [54]:
# 인덱스 범위
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [57]:
arr[6:8] = [200, 201]
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [60]:
arr[:2] = 100
arr

array([100, 100,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [61]:
arr2 = np.arange(16).reshape(4, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
arr2[1]

array([4, 5, 6, 7])

In [63]:
arr2[1][1]

5

In [64]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [65]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [66]:
score_arr[score_arr >=90]

array([90, 95, 90])

In [67]:
score_arr[score_arr >= 70]

array([80, 90, 70, 85, 95, 90, 80, 75, 80])

In [68]:
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [69]:
a = np.array([10, 20, 30, 40, 50, 60, 70 ,80])
b = a > 50
print(b)

[False False False False False  True  True  True]


In [84]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x[1])
# print(x[5])
# print(x[3])

[4 5 6]


In [85]:
y = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(x[:,1])
print(x[:,1]+y[:,1])
print(x[:,0]+y[:,2])

[2 5 8]
[ 5 11 17]
[ 5 11 17]


In [87]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
i = [1, 3, 5]
j = [2, 4, 6]
print(a[i])
print(a[j])

[20 40 60]
[30 50 70]


In [89]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[:][1])

[2, 12]


In [90]:
print(list1[1][:])

[2, 12]


In [91]:
print(list1[1][:1])

[2]


In [93]:
np_ary = np.array(list1)
print(np_ary[:, 1])

[11 12 13]


In [95]:
a = np.array([10, 20, 30, 40, 50, 60])
b = np.array(a[1:6:2])
print('b: ', b)
b[1] = 10
print('b: ', b)
print('a: ', a)
type(b)

b:  [20 40 60]
b:  [20 10 60]
a:  [10 20 30 40 50 60]


numpy.ndarray

In [96]:
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [97]:
arr + 2

array([3, 4, 5, 6])

In [98]:
arr * 2

array([2, 4, 6, 8])

In [106]:
arr1 = np.arange(0, 12).reshape(3, 4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
arr1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [108]:
arr1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [109]:
arr + arr1

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [110]:
arr * arr1

array([[ 0,  2,  6, 12],
       [ 4, 10, 18, 28],
       [ 8, 18, 30, 44]])

In [111]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [113]:
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [116]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16], dtype=int32)

In [118]:
# 제곱근(루트)
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [119]:
# exp(지수승)
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [120]:
# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [121]:
# 더하기
np.add(arr, arr1)

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [124]:
# 합계
np.sum(arr)

10

In [125]:
# 누적합
np.cumsum(arr)

array([ 1,  3,  6, 10], dtype=int32)

In [126]:
# 평균
np.mean(arr)

2.5

In [127]:
# 편차
np.var(arr)

1.25

In [128]:
# 표준편차
np.std(arr)

1.118033988749895

In [129]:
# 최소값
np.min(arr)

1

In [130]:
# 최대값
np.max(arr)

4

In [131]:
# 최소값의 인덱스
np.argmin(arr)

0

In [132]:
# 최대값의 인덱스
np.argmax(arr)

3

In [133]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = x * y
print(z)

[ 4 10 18]


## 변형 transpose()

In [134]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [135]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [136]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [138]:
arr3d = np.arange(27).reshape(3, 3, 3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
arr3d.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [141]:
arr3d.transpose()

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [142]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [146]:
np.save('array', arr)

In [149]:
load_arr = np.load('array.npy')

In [150]:
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [151]:
np.linspace(0, 15, 3)

array([ 0. ,  7.5, 15. ])

In [153]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [156]:
print(np.linspace(0, 20, 5, retstep=True))
print(np.linspace(0, 20, 5, retstep=False))

(array([ 0.,  5., 10., 15., 20.]), 5.0)
[ 0.  5. 10. 15. 20.]


In [158]:
print(np.linspace(0, 12, 4, endpoint = False))
print(np.linspace(0, 12, 4, endpoint = True))

[0. 3. 6. 9.]
[ 0.  4.  8. 12.]
